### ISSUE TITLE
Provide a persistent rule storage backend, other than in-memory db

### ISSUE THREAD

**Issue by rshriram** [amalgam8/controller#43]
We need to be able to store the controller rules in an external backend datastore: Redis or CouchDB/Cloudant).

Right now, the code is using a memoryCloudantDB, which would look better if renamed as a generic entity like, 'RulesDB'. Then depending on the underlying runtime/PaaS, different storage backends can be added by implementing the RulesDB storage adapter interface.

**Comment by ijsnellf** [comment]
This is resolved by https://github.com/amalgam8/controller/pull/56.
