### ISSUE TITLE
Services are being dropped over time

### ISSUE THREAD

**Issue by dcberg** [amalgam8/controller#5]
Have a situation where I am running the bookinfo demo and when I have the docker containers running for 18+ hours (Docker local) I am noticing that amalgam8 is loosing track of the running services. In this case the **a8ctl service-list** begins to loose track of the running service versions. Eventually the list drops to zero services.

**Comment by zcahana** [comment]
This is likely caused by amalgam8/sidecar#9.

**Comment by ijsnellf** [comment]
This should be resolved now that amalgam8/sidecar#9 is closed.
